[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
redis = "0.24.0"
serde = {version="1.0.217", features=["derive"]}
serde_json = "1.0.134"

[dev-dependencies]
assert_float_eq = "1"
serial_test = "2.0"
